<div>
<style type="text/css">
<!--
p#newfbmembers{margin:0 auto;padding:1em 1px;overflow:hidden;text-align:center;color:#FFF;background:#3B5998;font-size:3em;font-weight:bold;}
-->
</style>
<script type="text/javascript"> 
<!--
document.write('<p>Neue Facebook-Mitglieder, seitdem diese Seite aufgerufen wurde:<\/p>\n');
document.write('<p id="newfbmembers"><\/p>\n');
document.write('<p>Weltweit hat das Netzwerk 600 Millionen Nutzer - und in jeder Sekunde kommen acht neue Mitglieder dazu. (Quelle: <a href="http:\/\/www.socialbakers.com\/">SocialBakers</a>; Stand: Januar 2011)<\/p>\n');
function CountUp() {		
	totalnumber = Math.floor(totalnumber + 1);
	var totalstring = "" + totalnumber; //Tausendschoen(totalnumber);
	document.getElementById("newfbmembers").innerHTML = totalstring;
	setTimeout("CountUp()", 125);
}
var totalnumber = 0;
CountUp();
// -->
</script><p>Neue Facebook-Mitglieder, seitdem diese Seite aufgerufen wurde:</p>
<p id="newfbmembers">1292</p>
<p>Weltweit hat das Netzwerk 600 Millionen Nutzer - und in jeder Sekunde kommen acht neue Mitglieder dazu. (Quelle: <a href="http://www.socialbakers.com/">SocialBakers</a>; Stand: Januar 2011)</p>

<noscript>
&lt;p&gt;Weltweit hat das Netzwerk 600 Millionen Nutzer - und in jeder Sekunde kommen acht neue Mitglieder dazu. (Quelle: &lt;a href="http://www.socialbakers.com/"&gt;SocialBakers&lt;/a&gt;; Stand: Januar 2011)&lt;/p&gt;
</noscript></div>