<?php 
include_once ( '../init.php' );
?>
<div class="aa-fb-demo">
	<div class="page-header well">
	    <h1><?=__p("Facebook Demo")?> <small><?=__p("See Facebook Plugins and functionality in action?")?></small></h1>
	</div>
	<div class="row">
		<div class="span5">
			<h3>Like-Button</h3>
			<p>
				<div class="fb-like" data-href="<?php echo $aa['fb']['share_url']; ?>" data-send="true" data-width="400" data-show-faces="true"></div>
				For more info check the <a href="https://developers.facebook.com/docs/reference/plugins/like/" target="_blank">Facebook Like Button Documentation</a>.
			</p>
		</div>
		<div class="span5">
			<h3>Send-Button</h3>
			<p>
				<div class="fb-like" data-href="<?php echo $aa['fb']['share_url']; ?>" data-send="true" data-width="400" data-show-faces="true"></div>
				For more info check the <a href="https://developers.facebook.com/docs/reference/plugins/send/" target="_blank">Facebook Send Button Documentation</a>.
			</p>
		</div>
	</div>
</div>