<?php 
include_once ( '../init.php' );
?>

<h1>Form validation demo</h1>


<hr />
<h2>Modal form validation demo</h2>
<button class="btn btn-primary" href="#myModal" data-toggle="modal"><i class="icon-pencil icon-white"></i> Open form</button>

<div class="modal hide fade" id="myModal">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3>Modal form validation demo</h3>
	</div>
	<div class="modal-body">

		<form class="form-horizontal">
			<div class="control-group">
				<label class="control-label" for="inputName">Name</label>
				<div class="controls">
					<input type="text" id="inputName" placeholder="Your name" class="required">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="inputEmail">Email</label>
				<div class="controls">
					<input type="text" id="inputEmail" placeholder="Your email address" class="required email">
				</div>
			</div>
			<div class="control-group">
				<div class="controls">
					<label class="checkbox"> <input type="checkbox"> Remember me
					</label>
					<button type="submit" class="btn">Sign in</button>
				</div>
			</div>
		</form>

	</div>
	<div class="modal-footer">
		<a href="#" class="btn">Close</a>
	</div>
</div>


<script>

$(document).ready(function() {
	$("form").validate(bootstrap_form);
});

/* This will make the jQuery validation plugin work with bootstrap forms */
var bootstrap_form = {
	errorClass : "error",
	validClass : "success",
	errorElement : "span",
	highlight : function(element, errorClass, validClass) {
		if (element.type === 'radio') {
			this.findByName(element.name).closest(".control-group")
					.removeClass(validClass).addClass(errorClass);
		} else {
			$(element).closest(".control-group").removeClass(validClass)
					.addClass(errorClass);
		}
	},
	unhighlight : function(element, errorClass, validClass) {
		if (element.type === 'radio') {
			this.findByName(element.name).closest(".control-group")
					.removeClass(errorClass).addClass(validClass);
		} else {
			$(element).closest(".control-group").removeClass(errorClass)
					.addClass(validClass);
		}
	},
	errorPlacement : function(error, element) {
		error.prependTo(element.closest(".control-group"));
	},

	rules : {
		email : {
			required : true,
			email : true
		},
		name : {
			required : true,
			minlength : 5
		}
	}
}
</script>


