<?php 
include_once ( '../init_session.php' );

$form=new Frd_Form();
$form->setAttr("id","test_form");

$form->addField("text","name",'','Name');
$form->addField("text","email",'','Email');

$form->addSubmitButton("Save");


?>


<div class="terms-and-conditions">
	<div class="page-header well">
	    <h1><?=__p("page_welcome_header")?> <small><?=__p("What are the prizes? Who can participate?")?></small></h1>
	</div>
	<div class="row-fluid">
		<div class="terms-body">
       <?php echo $form->render(); ?>
		</div>
	</div>
</div>


<script>

$(document).ready( function(){

      hide_loading();

      <?php echo $form->renderJs(); ?>
});

</script>


