<?php 
include_once ( '../init_session.php' );
$translate->setLocale("de_DE");
?>
<div class="terms-and-conditions">
	<div class="page-header well">
	    <h1><?=__p("page_welcome_header")?> <small><?=__p("What are the prizes? Who can participate?")?></small></h1>
	</div>
	<div class="row-fluid">
		<div class="terms-body">
			<?php  var_dump($session->translation['de_DE']);?>
			<?php 
			
			
			?>
			<?php __p('hello'); ?>
		</div>
	</div>
</div>
<script>
	$(document).ready( function(){
		
		hide_loading();
		
	});
</script>
