<div id="loading_screen">
    <div class="loading"></div>
</div>
<script type="text/javascript">
    //show loading div
    function show_loading() {
        document.getElementById("loading_screen").style.display = 'block';
    }

    //hide loading div
    function hide_loading() {
        document.getElementById("loading_screen").style.display = 'none';
    }

    show_loading();

</script>