<?php 
include_once ( '../init.php' );
?>
<div class="localization">
	<div class="row">
		<div class="span10">
			<h1>Localization demo</h1>
			<p>You can use localization in this app template using two php-functions:
			<ol>
				<li>__t("identifier")  --> Translate identifier</li>
				<li>__p("identifier")  --> Translate and print identifier</li>
			</ol>
			If you use these functions in your php-code they will replace the identifier with the currently selected language. All identifier and all available languages can be setup in the "Locale" tab of your app-model. 
			</p>
			<h2>Using variables</h2>
			<p></p>
		</div>
	</div>
</div>