<?php 
include_once ( '../init.php' );
?>
<h1>Module: Newsletter</h1>
<p>Use a double-opt-in Newsletter registration with just two lines of code. :-)</p>

<h2>Requirements</h2>
<ul>
<li>App-Arena App-Manager Connection</li>
</ul>

<h2>Use it...</h2>
<h3>With javascript</h3>
<pre>
<script src="modules/newsletter/newsletter.js"></script>
<script>
send_newsletter(aa_inst_id, email, name);
</script>
</pre>

<h3>With php</h3>
<pre>
include_once 'modules/newsletter/send_newsletter_confirmation.php';
</pre>

<h2>Demo</h2>
<div class="alert">
This still has to be written
</div>