<?php 
	include_once ( '../init.php' );
?>
<script type="text/javascript" src="modules/registration/registration.js"></script>

<h1>Registration demo</h1>

<div class="alert alert-info">
	<div>Include 'modules/registration/registration.js' to use the registration functions:</div>
    <div>&lt;script src="modules/registration/registration.js" type="text/javascript" /&gt;</div>
    <div>Note that there has to be valid data for the database connection in root/config.php.</div>
</div>

<hr />

<div class="row">
	<div class="span10">
		<div id="container_connect">
			<h2>Facebook connect</h2>
			<hr />
        </div>
    </div>
</div>
<div class="row">
    <div class="span5">
        <p><strong id="user_profile"></strong></p>
        <button class="btn btn-primary" onclick="register_via_connect();"><i class="icon-retweet icon-white"></i> Connect</button>
        <span id="progress-connect" class="hide progress"><img src="img/loading_progress.gif" /></span>
        <label class="control-label" for="scope" title="enter a FB scope list here, such as 'email' or 'email,publish_stream'">Scope
            <input type="text" value="email" id="scope" name="scope" />
        </label>
    </div>
    <div class="span4">
        <span>
            Connect your users with a simple login procedure.
            The FB-API is used to log the user in and return a
            JSON containing the data you requested through the
            scope(s).
        </span>
        <span><a href="https://developers.facebook.com/docs/reference/javascript/FB.login/">https://developers.facebook.com/docs/reference/javascript/FB.login/</a></span>
        <span><a href="https://developers.facebook.com/docs/reference/javascript/FB.api/">https://developers.facebook.com/docs/reference/javascript/FB.api/</a></span>
    </div>
</div>
<hr />
<div class="row">
    <div class="span10">
        <div id="container_register">
            <h2>Facebook registration</h2>
            <hr />
        </div>
    </div>
</div>
<div class="row">
    <div class="span5">
        <button class="btn btn-primary" onclick="register_via_widget();"><i class="icon-random icon-white"></i> refresh Registration</button>
        <!--<button class="btn btn-primary" onclick="fb_register_debug();"><i class="icon-random icon-white"></i> refresh Registration</button>-->

        <span id="progress-register" class="hide progress"><img src="img/loading_progress.gif" /></span>
        <label class="control-label" for="fields" title="enter a FB field list here, such as 'name' or 'name,birthday,gender,location,email'">Fields
            <input type="text" value="name" id="fields" name="fields" />
        </label>
        <label class="control-label" for="url" title="enter an url which will be opened by the registration plugin">URL
            <input type="text" value="https://www.app-arena.com/app/aa_template/dev/modules/registration/save_user.php?aa_inst_id=<?php echo $aa_inst_id; ?>" id="url" name="url" />
        </label>
    </div>
    <div class="span4">
        <span>
            Connect your users with a registration procedure.
            XFBML is used to log the user in and return a
            JSON containing the data you requested through the
            field(s).
        </span>
        <span><a href="https://developers.facebook.com/docs/plugins/registration/">https://developers.facebook.com/docs/plugins/registration/</a></span>
    </div>
</div>
<hr />
<div class="row">
    <span id="fb_registration_widget">
    </span>
</div>
<hr />
<div class="row">
	<div class="span10">
		<div id="container_form">
			<h2>Form registration</h2>
			<hr />
        </div>
    </div>
</div>
<div class="row">
    <div class="span5">
        <form class="form-registration" action="javascript:register_via_form();" id="myForm">
            <div class="control-group">
                <label class="control-label" for="name">Name</label>
                <div class="controls">
                    <!-- The id/name attribute is needed by the validation. For the registration you should supply at least an id. -->
                    <input type="text" id="name" name="name" placeholder="Your name" class="required">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="email">Email</label>
                <div class="controls">
                    <input type="text" id="email" name="email" placeholder="Your email address" class="required email">
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <label class="checkbox"><input id="option_1" type="checkbox"> Yes, we can!</label>
                    <button type="submit" class="btn"><i class="icon-envelope"></i> Submit</button>
                </div>
            </div>
        </form>
        <span id="progress-form" class="hide progress"><img src="img/loading_progress.gif" /></span>
    </div>
    <div class="span4">
        <span>
            Connect your users with a simple form.
            The FB-API is not used here.
            This will return a JSON object containing the data
            from fields you put into the form.
        </span>
    </div>
</div>

<hr />
<div id="container_log" class="row hide">
	<div class="span10">
		<h2>Log action</h2>
		<hr />
		<button class="btn btn-primary" onclick="log_action();"><i class="icon-download-alt icon-white"></i> Log action for current user</button>
		<span id="progress-log" class="hide progress"><img src="img/loading_progress.gif" /></span>
		<label class="control-label" for="action" title="Enter an action type here, such as 'register' or 'invite'">Action to log
			<input type="text" value="register" id="action" name="action" />
		</label>
        <label class="control-label" for="data" title="Enter some data here, like &quot;What was the user registring for actually?&quot;">Data to log
            <input type="text" value="sample data" id="data" name="data" />
        </label>
	</div>
</div>

<h1>Module: Newsletter</h1>
<p>Use a double-opt-in Newsletter registration with just two lines of code. :-)</p>

<h2>Requirements</h2>
<ul>
    <li>App-Arena App-Manager Connection</li>
</ul>

<h2>Use it...</h2>
<h3>With javascript</h3>
<pre>
&lt;script src="modules/newsletter/newsletter.js" /&gt;
send_newsletter(aa_inst_id, email, name);
</pre>

<h3>With php</h3>
<pre>
include_once 'modules/newsletter/send_newsletter_confirmation.php';
</pre>

<h2>Demo</h2>
<div class="alert">
    This still has to be written
</div>

<script>
$(document).ready(function() {
	$(".form-registration").validate( $.register_bootstrap_form ); // use the register_bootstrap_form variable from the registration.js
    $.register_fb_widget( 'name,birthday,gender,location,email', 'https://www.app-arena.com/app/aa_template/dev/modules/registration/save_user.php?aa_inst_id=' + aa_inst_id, '#fb_registration_widget' ); // show demo registration widget
    //register_fb_widget( 'name,birthday,gender,location,email', 'https://www.app-arena.com/app/aa_template/dev/modules/registration/save_user.php?aa_inst_id=' + aa_inst_id, '#fb_registration_widget' ); // show demo registration widget
});

function register_via_connect() {
    disableForm();
    $( '#progress-connect' ).show();
    var scope = $( '#scope' ).val();
    $.register_fb_connect( scope, callbackSuccessConnect );
}
function callbackSuccessConnect( data ) {

    $( '#progress-connect' ).after(
        '<button class="btn btn-success" id="saveUserData" onclick="$.register_save_user_data();">' +
        '<i class="icon-download-alt icon-white"></i> Save user data</button>'
    );
    $( '#progress-connect' ).hide();
    $( '#user_profile' ).html(
        $.register_user_data[ 'name' ] + '&nbsp;&nbsp;&nbsp;'
        + '<a href="https://www.facebook.com/' + $.register_user_data[ 'key' ] + '" target="_blank">'
        + '<img class="profile-picture" src="https://graph.facebook.com/'
        + $.register_user_data[ 'key' ]
        + '/picture?type=square" title="visit the users facebook profile..." /></a>'
    );
    $( '#container_log' ).fadeIn( 300 );
    enableForm();
}

function register_via_widget() {
    disableForm();
    $( '#progress-register' ).show();
    var url = $( '#url').val();
    var fields = $( '#fields' ).val();
    var put_to = '#fb_registration_widget';
    var response = $.register_fb_widget( fields, url, put_to );
    enableForm();
    $( '#progress-register' ).hide();
}

function register_via_form() {
    disableForm();
    $( '#progress-form' ).show();
    $.register_form( '#myForm', callbackSuccessForm );
}
function callbackSuccessForm( data ) {

    $( '#progress-form' ).after(
        '<button class="btn btn-success" id="saveUserData" onclick="$.register_save_user_data(' + aa_inst_id + ');">' +
        '<i class="icon-download-alt icon-white"></i> Save user data</button>'
    );
    $( '#progress-form' ).hide();
    $( '#container_log' ).fadeIn( 300 );
    enableForm();
}

function log_action() {

    disableForm();
    $( '#progress-log' ).show();
    var action = $( '#action' ).val();
    var data = $( '#data' ).val();
    $.register_log_action( aa_inst_id, action, data, callbackSuccessLog );

}
function callbackSuccessLog( data ) {

    $( '#progress-log' ).hide();
    enableForm();

}
</script>