<?php 
	include_once ( '../init.php' );
?>
<div class="terms-and-conditions">
	<div class="page-header well">
	    <h1><?=__p("Terms & Conditions")?> <small><?=__p("What are the prizes? Who can participate?")?></small></h1>
	</div>
	<div class="row-fluid">
		<div class="terms-body">
			<?=$session->config['terms_and_conditions']['value'];?>
		</div>
	</div>
</div>
<script>
	$(document).ready( function(){
		
		hide_loading();
		
	});
</script>