<?php 
include_once ( '../init.php' );
?>
<div class="welcome-container">
	<div class="row">
		<div class="span10">
			<div class="welcome-header">
				<h1>App-Arena.com App template</h1>
				<p>Easy facebook app template, offering a wide set of frequently used functionality.</p>
				<p>The app template contains many functions which are used in most facebook apps and do not need to be implemented on and on...<br />
				
				<strong>Functionality overview:</strong>
				<ul>
					<li>Load new templates using jquery animations</li>
					<li>Sending emails using templates incl. Newsletter double opt in registration</li>
					<li>Twitter Bootstrap: Forms, Navigation, Modals, Carousel, ...</li>
					<li>Facebook Social functionality (Invite, Send, Share, Like, Comment)</li>
					<li>Facebook Authentification - Auth user and save him to the database</li>
					<li>Facebook Open Graph Integration</li>
					<li>Facebook Fangate</li>
					<li>Admin panel</li>
					<li>Database connection - necessary tables will created automatically</li>
					<li>Localization - Publish apps in different languages</li>
					<li>App-Arena.com App-Manager connection: Develop once, duplicate on mouse-click</li>
				</ul>
				
				<p>
					To get to know all the functionality this template is offering you, we created several template files, which integrate examples. So you can just adapt these examples to your needs.
					<ul>
						<li><a onclick="aa_tmpl_load('terms.phtml');">Terms & conditions</a></li>
						<li><a onclick="aa_tmpl_load('fb-demo.phtml');">Facebook social features</a></li>
						<li><a onclick="aa_tmpl_load('localization.phtml');">Localization</a></li>
					</ul>
				</p>
			</div>
		</div>
	</div>

</div> <!-- End welcome div live -->

<script>
$(document).ready( function(){
	hide_loading();
});
</script>
