<?php 
include_once ( '../init.php' );
?>
<div class="welcome-container">
	<div class="row">
		<div class="span10">
			<div class="welcome-header">
				<h1><?php __p("translate_me"); ?></h1>
			</div>
		</div>
	</div>
	
		<div class="hero-unit teaser">
			<h1>Welcome to our App-Arena Demo App</h1>	
		</div>

</div> <!-- End welcome div live -->

<script>
$(document).ready( function(){
	hide_loading();
});
</script>
